// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Configuration;
using LinqToDB.Data;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModel
{
	public partial class LifeManagerDb : DataConnection
	{
		#region Schemas
		public void InitSchemas()
		{
			Adm = new AdmSchema.DataContext(this);
			Test = new TestSchema.DataContext(this);
		}

		public AdmSchema.DataContext  Adm  { get; set; } = null!;
		public TestSchema.DataContext Test { get; set; } = null!;
		#endregion

		public LifeManagerDb()
		{
			InitSchemas();
			InitDataContext();
		}

		public LifeManagerDb(string configuration)
			: base(configuration)
		{
			InitSchemas();
			InitDataContext();
		}

		public LifeManagerDb(LinqToDBConnectionOptions<LifeManagerDb> options)
			: base(options)
		{
			InitSchemas();
			InitDataContext();
		}

		partial void InitDataContext();
	}
}
