// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB;
using LinqToDB.Mapping;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModel
{
	public static partial class TestSchema
	{
		public partial class DataContext
		{
			private readonly IDataContext _dataContext;

			public ITable<TableName> TableNames => _dataContext.GetTable<TableName>();

			public DataContext(IDataContext dataContext)
			{
				_dataContext = dataContext;
			}
		}

		[Table("table_name", Schema = "test")]
		public class TableName
		{
			[Column("column_name")] public int? ColumnName { get; set; } // integer
		}
	}
}
