//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1573, 1591

using System;
using System.Collections.Generic;
using System.Linq;

using LinqToDB;
using LinqToDB.Configuration;
using LinqToDB.Mapping;

namespace LM.Data
{
	/// <summary>
	/// Database       : life_manager
	/// Data Source    : tcp://localhost:5432
	/// Server Version : 14.1
	/// </summary>
	public partial class DbContext : LinqToDB.Data.DataConnection
	{
		public ITable<claims> claims { get { return this.GetTable<claims>(); } }
		public ITable<user>   user   { get { return this.GetTable<user>(); } }

		protected void InitMappingSchema()
		{
		}
	}

	[Table(Schema="adm", Name="claims")]
	public partial class claims
	{
		[Column(DbType="uuid", DataType=LinqToDB.DataType.Guid), PrimaryKey, NotNull]
		public Guid id { get; set; } // uuid

		[Column(DbType="uuid", DataType=LinqToDB.DataType.Guid),    Nullable]
		public Guid? f_user_id { get; set; } // uuid

		[Column(DbType="text", DataType=LinqToDB.DataType.Text),    Nullable]
		public string c_key { get; set; } // text

		[Column(DbType="text", DataType=LinqToDB.DataType.Text),    Nullable]
		public string c_value { get; set; } // text

		#region Associations

		/// <summary>
		/// claims_user_null_fk (adm.user)
		/// </summary>
		[Association(ThisKey="f_user_id", OtherKey="id", CanBeNull=true)]
		public user f_user { get; set; }

		#endregion
	}

	[Table(Schema="adm", Name="user")]
	public partial class user
	{
		[Column(DbType="text",     DataType=LinqToDB.DataType.Text) ,    Nullable]
		public string mail { get; set; } // text

		[Column(DbType="text",     DataType=LinqToDB.DataType.Text) ,    Nullable]
		public string password { get; set; } // text

		[Column(DbType="uuid",     DataType=LinqToDB.DataType.Guid) , PrimaryKey, NotNull]
		public Guid id { get; set; } // uuid

		[Column(DbType="text",     DataType=LinqToDB.DataType.Text) ,    Nullable]
		public string user_name { get; set; } // text

		[Column(DbType="smallint", DataType=LinqToDB.DataType.Int16, Precision=16, Scale=0),    Nullable]
		public short? role { get; set; } // smallint

		[Column(DbType="text",     DataType=LinqToDB.DataType.Text) ,    Nullable]
		public string normalize_name { get; set; } // text
	}

	public static partial class TableExtensions
	{
		public static claims Find(this ITable<claims> table, Guid id)
		{
			return table.FirstOrDefault(t =>
				t.id == id);
		}

		public static user Find(this ITable<user> table, Guid id)
		{
			return table.FirstOrDefault(t =>
				t.id == id);
		}
	}
}
