//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1573, 1591

using System;

using LinqToDB;
using LinqToDB.Configuration;
using LinqToDB.Mapping;

namespace Database
{
	/// <summary>
	/// Database       : rabbit_test
	/// Data Source    : tcp://localhost:5432
	/// Server Version : 14.1
	/// </summary>
	public partial class DbContext : LinqToDB.Data.DataConnection
	{
		public ITable<messages> messages { get { return this.GetTable<messages>(); } }

		protected void InitMappingSchema()
		{
		}
	}

	[Table(Schema="rabbit", Name="messages")]
	public partial class messages
	{
		[Column(DbType="bigint", DataType=LinqToDB.DataType.Int64, Precision=64, Scale=0), Nullable]
		public long? id { get; set; } // bigint
	}
}
